sudo: required
dist: trusty
language: node_js
node_js:
    - "6.3.1"
env:
  global:
    - ENCRYPTION_LABEL: "57b55b7ed9a3"
    - COMMIT_AUTHOR_EMAIL: "travis@codezilla.nl"
addons:
  packages:
    - unzip
    - google-chrome-stable
script:
    - npm run test-e2e -- --env ci
before_script:
    - npm install
    - npm run build
after_success:
    - ./tools/ci/deploy.sh
