sudo: required
dist: trusty
language: node_js
node_js:
    - "6.3.1"
env:
    global:
    - ENCRYPTION_LABEL: "1b5469661a88"
    - COMMIT_AUTHOR_EMAIL: "travis@codezilla.nl
addons:
  packages:
    - unzip
    - google-chrome-stable
script:
    - npm run test-e2e -- --env ci
before_script:
    - npm install
after_success:
    - ./tools/ci/deploy.sh
